#!/usr/bin/python

import struct
import os

ghdl_a = "ghdl -a -v"
ghdl_e = "ghdl -e -v"
ghdl_r_1 = "ghdl -r "
ghdl_r_2 = "--vcd="
ghdl_r = ghdl_r_1 + "adder_tb" + ghdl_r_2 + "adder.vcd"

os.system ("{0} '{1}'".format(ghdl_a, adder_tb.vhdl))
os.system ("{0} '{1}'".format(ghdl_e, adder_tb))
os.system ("'{}'".format(ghdl_r))
